---
- name: Ensure sudo is installed
  yum:
    name: sudo
    state: present
  tags: download-sudo

- name: install EPEL repo
  become: yes
  yum: name=epel-release state=present

- name: Include service installation tasks
  include_tasks: "rabbitmq-service.yml"
  tags: rabbitmq-service

- name: Include service configuration tasks
  include_tasks: "rabbitmq-configure.yml"
  tags: rabbitmq-config

- name: Include service user management tasks
  include_tasks: "rabbitmq-users.yml"
  tags: rabbitmq-users
