---
- name: Ensure RabbitMQ is installed
  yum:
    name: rabbitmq-server
    # state: present, in order not to upgrade any package to an untested version
    state: present
  become: yes
  tags: rabbitmq-service

- name: Ensure RabbitMQ is started
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: yes
  tags: rabbitmq-service
