---
- name: Ensure RabbitMQ is installed
  yum:
    name: rabbitmq-server
    state: latest
  become: yes
  tags: rabbitmq-service

- name: Ensure RabbitMQ is started
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: yes
  tags: rabbitmq-service
