---
- name: Ensure RabbitMQ data directory exist
  file:
    path: '{{ data_root }}/rabbitmq'
    state: 'directory'
    owner: 'rabbitmq'
    group: 'rabbitmq'
    mode: '0755'
  become: yes
  when: data_root is defined
  tags: rabbitmq-config

- name: Copy RabbitMQ environment configuration file
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
    mode: 0644
  become: yes
  notify:
  - Restart RabbitMQ
  when: data_root is defined
  tags: rabbitmq-config

- name: Ensure wanted plugins are enabled
  template:
    src: 'enabled_plugins.j2'
    dest: '/etc/rabbitmq/enabled_plugins'
    mode: 0644
  become: 'yes'
  when: enabled_plugins | length > 0
  notify: Restart RabbitMQ
  tags: rabbitmq-config
